Set specific pytorch version for major platforms (linux, win32, darwin)
ArneBinder/pie-datasets pull request #132
Opened 2024-07-09 10:23 UTC by kai-car

Current dependency setup failed on macOS with following error message:

```  
 - Installing torch (2.3.1): Failed

  RuntimeError

  Unable to find installation candidates for torch (2.3.1)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install torch. 
```

This is due to the fact that torch version 2.3.1 apparently does not exist for macOS currently. Therefore, we adjusted the version of torch in pyproject.yml to the range `>=2.1.0, <2.3.0` for macOS.

2024-07-09 12:11 UTC, ArneBinder requested changes
I just looked at pytorch.org again and it seems there is at least version `2.3.0` for OSX, see https://pytorch.org/get-started/previous-versions/#osx-1. Can you investigate, if the reasoning from the PR description is really correct? The goal is to really drill down on the issue and at the end having a fix with the smallest possible surface. These kinds of specific version settings need to be (more or less manually) maintained and the fix needs to be ported to all the other PIE repos, too, so it may have a certain impact.

2024-07-09 15:31 UTC, kai-car commented
Took me some time, but it seems the issue on my side occurred because PyTorch no longer supports macOS x86_64 (Intel Chips) from Release 2.3.0 on, as Apple stopped building Macs with Intel Chips. See https://dev-discuss.pytorch.org/t/pytorch-macos-x86-builds-deprecation-starting-january-2024/1690

2024-07-10 08:58 UTC, ArneBinder commented
Thanks a lot of your investigation! Can we define the version explicitly for `x86_64`, i.e. via sth like `platform_machine == 'x86_64'` in `markers`? see https://python-poetry.org/docs/dependency-specification/#using-environment-markers

2024-07-12 10:01 UTC, ArneBinder approved these changes

2024-07-12 10:05 UTC, merged